spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_reservation_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    change-log: classpath:db/liquibase/db-changelog-master.xml
    enabled: true